<?php

declare(strict_types=1);

namespace App\Domain\Money;

enum Currency: string
{
    /**
     * @return non-empty-string
     */
    public function getCurrencyName(): string
    {
        return match ($this) {
            self::ADP => 'Andorran Peseta',
            self::AED => 'United Arab Emirates Dirham',
            self::AFA => 'Afghan Afghani (1927–2002)',
            self::AFN => 'Afghan Afghani',
            self::ALK => 'Albanian Lek (1946–1965)',
            self::ALL => 'Albanian Lek',
            self::AMD => 'Armenian Dram',
            self::ANG => 'Netherlands Antillean Guilder',
            self::AOA => 'Angolan Kwanza',
            self::AOK => 'Angolan Kwanza (1977–1991)',
            self::AON => 'Angolan New Kwanza (1990–2000)',
            self::AOR => 'Angolan Readjusted Kwanza (1995–1999)',
            self::ARA => 'Argentine Austral',
            self::ARL => 'Argentine Peso Ley (1970–1983)',
            self::ARM => 'Argentine Peso (1881–1970)',
            self::ARP => 'Argentine Peso (1983–1985)',
            self::ARS => 'Argentine Peso',
            self::ATS => 'Austrian Schilling',
            self::AUD => 'Australian Dollar',
            self::AWG => 'Aruban Florin',
            self::AZM => 'Azerbaijani Manat (1993–2006)',
            self::AZN => 'Azerbaijani Manat',
            self::BAD => 'Bosnia-Herzegovina Dinar (1992–1994)',
            self::BAM => 'Bosnia-Herzegovina Convertible Mark',
            self::BAN => 'Bosnia-Herzegovina New Dinar (1994–1997)',
            self::BBD => 'Barbadian Dollar',
            self::BDT => 'Bangladeshi Taka',
            self::BEC => 'Belgian Franc (convertible)',
            self::BEF => 'Belgian Franc',
            self::BEL => 'Belgian Franc (financial)',
            self::BGL => 'Bulgarian Hard Lev',
            self::BGM => 'Bulgarian Socialist Lev',
            self::BGN => 'Bulgarian Lev',
            self::BGO => 'Bulgarian Lev (1879–1952)',
            self::BHD => 'Bahraini Dinar',
            self::BIF => 'Burundian Franc',
            self::BMD => 'Bermudan Dollar',
            self::BND => 'Brunei Dollar',
            self::BOB => 'Bolivian Boliviano',
            self::BOL => 'Bolivian Boliviano (1863–1963)',
            self::BOP => 'Bolivian Peso',
            self::BOV => 'Bolivian Mvdol',
            self::BRB => 'Brazilian New Cruzeiro (1967–1986)',
            self::BRC => 'Brazilian Cruzado (1986–1989)',
            self::BRE => 'Brazilian Cruzeiro (1990–1993)',
            self::BRL => 'Brazilian Real',
            self::BRN => 'Brazilian New Cruzado (1989–1990)',
            self::BRR => 'Brazilian Cruzeiro (1993–1994)',
            self::BRZ => 'Brazilian Cruzeiro (1942–1967)',
            self::BSD => 'Bahamian Dollar',
            self::BTN => 'Bhutanese Ngultrum',
            self::BUK => 'Burmese Kyat',
            self::BWP => 'Botswanan Pula',
            self::BYB => 'Belarusian Ruble (1994–1999)',
            self::BYN => 'Belarusian Ruble',
            self::BYR => 'Belarusian Ruble (2000–2016)',
            self::BZD => 'Belize Dollar',
            self::CAD => 'Canadian Dollar',
            self::CDF => 'Congolese Franc',
            self::CHE => 'WIR Euro',
            self::CHF => 'Swiss Franc',
            self::CHW => 'WIR Franc',
            self::CLE => 'Chilean Escudo',
            self::CLF => 'Chilean Unit of Account (UF)',
            self::CLP => 'Chilean Peso',
            self::CNH => 'Chinese Yuan (offshore)',
            self::CNX => 'Chinese People’s Bank Dollar',
            self::CNY => 'Chinese Yuan',
            self::COP => 'Colombian Peso',
            self::COU => 'Colombian Real Value Unit',
            self::CRC => 'Costa Rican Colón',
            self::CSD => 'Serbian Dinar (2002–2006)',
            self::CSK => 'Czechoslovak Hard Koruna',
            self::CUC => 'Cuban Convertible Peso',
            self::CUP => 'Cuban Peso',
            self::CVE => 'Cape Verdean Escudo',
            self::CYP => 'Cypriot Pound',
            self::CZK => 'Czech Koruna',
            self::DDM => 'East German Mark',
            self::DEM => 'German Mark',
            self::DJF => 'Djiboutian Franc',
            self::DKK => 'Danish Krone',
            self::DOP => 'Dominican Peso',
            self::DZD => 'Algerian Dinar',
            self::ECS => 'Ecuadorian Sucre',
            self::ECV => 'Ecuadorian Unit of Constant Value',
            self::EEK => 'Estonian Kroon',
            self::EGP => 'Egyptian Pound',
            self::ERN => 'Eritrean Nakfa',
            self::ESA => 'Spanish Peseta (A account)',
            self::ESB => 'Spanish Peseta (convertible account)',
            self::ESP => 'Spanish Peseta',
            self::ETB => 'Ethiopian Birr',
            self::EUR => 'Euro',
            self::FIM => 'Finnish Markka',
            self::FJD => 'Fijian Dollar',
            self::FKP => 'Falkland Islands Pound',
            self::FRF => 'French Franc',
            self::GBP => 'British Pound',
            self::GEK => 'Georgian Kupon Larit',
            self::GEL => 'Georgian Lari',
            self::GHC => 'Ghanaian Cedi (1979–2007)',
            self::GHS => 'Ghanaian Cedi',
            self::GIP => 'Gibraltar Pound',
            self::GMD => 'Gambian Dalasi',
            self::GNF => 'Guinean Franc',
            self::GNS => 'Guinean Syli',
            self::GQE => 'Equatorial Guinean Ekwele',
            self::GRD => 'Greek Drachma',
            self::GTQ => 'Guatemalan Quetzal',
            self::GWE => 'Portuguese Guinea Escudo',
            self::GWP => 'Guinea-Bissau Peso',
            self::GYD => 'Guyanaese Dollar',
            self::HKD => 'Hong Kong Dollar',
            self::HNL => 'Honduran Lempira',
            self::HRD => 'Croatian Dinar',
            self::HRK => 'Croatian Kuna',
            self::HTG => 'Haitian Gourde',
            self::HUF => 'Hungarian Forint',
            self::IDR => 'Indonesian Rupiah',
            self::IEP => 'Irish Pound',
            self::ILP => 'Israeli Pound',
            self::ILR => 'Israeli Shekel (1980–1985)',
            self::ILS => 'Israeli New Shekel',
            self::INR => 'Indian Rupee',
            self::IQD => 'Iraqi Dinar',
            self::IRR => 'Iranian Rial',
            self::ISJ => 'Icelandic Króna (1918–1981)',
            self::ISK => 'Icelandic Króna',
            self::ITL => 'Italian Lira',
            self::JMD => 'Jamaican Dollar',
            self::JOD => 'Jordanian Dinar',
            self::JPY => 'Japanese Yen',
            self::KES => 'Kenyan Shilling',
            self::KGS => 'Kyrgystani Som',
            self::KHR => 'Cambodian Riel',
            self::KMF => 'Comorian Franc',
            self::KPW => 'North Korean Won',
            self::KRH => 'South Korean Hwan (1953–1962)',
            self::KRO => 'South Korean Won (1945–1953)',
            self::KRW => 'South Korean Won',
            self::KWD => 'Kuwaiti Dinar',
            self::KYD => 'Cayman Islands Dollar',
            self::KZT => 'Kazakhstani Tenge',
            self::LAK => 'Laotian Kip',
            self::LBP => 'Lebanese Pound',
            self::LKR => 'Sri Lankan Rupee',
            self::LRD => 'Liberian Dollar',
            self::LSL => 'Lesotho Loti',
            self::LTL => 'Lithuanian Litas',
            self::LTT => 'Lithuanian Talonas',
            self::LUC => 'Luxembourgian Convertible Franc',
            self::LUF => 'Luxembourgian Franc',
            self::LUL => 'Luxembourg Financial Franc',
            self::LVL => 'Latvian Lats',
            self::LVR => 'Latvian Ruble',
            self::LYD => 'Libyan Dinar',
            self::MAD => 'Moroccan Dirham',
            self::MAF => 'Moroccan Franc',
            self::MCF => 'Monegasque Franc',
            self::MDC => 'Moldovan Cupon',
            self::MDL => 'Moldovan Leu',
            self::MGA => 'Malagasy Ariary',
            self::MGF => 'Malagasy Franc',
            self::MKD => 'Macedonian Denar',
            self::MKN => 'Macedonian Denar (1992–1993)',
            self::MLF => 'Malian Franc',
            self::MMK => 'Myanmar Kyat',
            self::MNT => 'Mongolian Tugrik',
            self::MOP => 'Macanese Pataca',
            self::MRO => 'Mauritanian Ouguiya (1973–2017)',
            self::MRU => 'Mauritanian Ouguiya',
            self::MTL => 'Maltese Lira',
            self::MTP => 'Maltese Pound',
            self::MUR => 'Mauritian Rupee',
            self::MVP => 'Maldivian Rupee (1947–1981)',
            self::MVR => 'Maldivian Rufiyaa',
            self::MWK => 'Malawian Kwacha',
            self::MXN => 'Mexican Peso',
            self::MXP => 'Mexican Silver Peso (1861–1992)',
            self::MXV => 'Mexican Investment Unit',
            self::MYR => 'Malaysian Ringgit',
            self::MZE => 'Mozambican Escudo',
            self::MZM => 'Mozambican Metical (1980–2006)',
            self::MZN => 'Mozambican Metical',
            self::NAD => 'Namibian Dollar',
            self::NGN => 'Nigerian Naira',
            self::NIC => 'Nicaraguan Córdoba (1988–1991)',
            self::NIO => 'Nicaraguan Córdoba',
            self::NLG => 'Dutch Guilder',
            self::NOK => 'Norwegian Krone',
            self::NPR => 'Nepalese Rupee',
            self::NZD => 'New Zealand Dollar',
            self::OMR => 'Omani Rial',
            self::PAB => 'Panamanian Balboa',
            self::PEI => 'Peruvian Inti',
            self::PEN => 'Peruvian Sol',
            self::PES => 'Peruvian Sol (1863–1965)',
            self::PGK => 'Papua New Guinean Kina',
            self::PHP => 'Philippine Peso',
            self::PKR => 'Pakistani Rupee',
            self::PLN => 'Polish Zloty',
            self::PLZ => 'Polish Zloty (1950–1995)',
            self::PTE => 'Portuguese Escudo',
            self::PYG => 'Paraguayan Guarani',
            self::QAR => 'Qatari Riyal',
            self::RHD => 'Rhodesian Dollar',
            self::ROL => 'Romanian Leu (1952–2006)',
            self::RON => 'Romanian Leu',
            self::RSD => 'Serbian Dinar',
            self::RUB => 'Russian Ruble',
            self::RUR => 'Russian Ruble (1991–1998)',
            self::RWF => 'Rwandan Franc',
            self::SAR => 'Saudi Riyal',
            self::SBD => 'Solomon Islands Dollar',
            self::SCR => 'Seychellois Rupee',
            self::SDD => 'Sudanese Dinar (1992–2007)',
            self::SDG => 'Sudanese Pound',
            self::SDP => 'Sudanese Pound (1957–1998)',
            self::SEK => 'Swedish Krona',
            self::SGD => 'Singapore Dollar',
            self::SHP => 'St. Helena Pound',
            self::SIT => 'Slovenian Tolar',
            self::SKK => 'Slovak Koruna',
            self::SLE => 'Sierra Leonean Leone',
            self::SLL => 'Sierra Leonean Leone (1964—2022)',
            self::SOS => 'Somali Shilling',
            self::SRD => 'Surinamese Dollar',
            self::SRG => 'Surinamese Guilder',
            self::SSP => 'South Sudanese Pound',
            self::STD => 'São Tomé & Príncipe Dobra (1977–2017)',
            self::STN => 'São Tomé & Príncipe Dobra',
            self::SUR => 'Soviet Rouble',
            self::SVC => 'Salvadoran Colón',
            self::SYP => 'Syrian Pound',
            self::SZL => 'Swazi Lilangeni',
            self::THB => 'Thai Baht',
            self::TJR => 'Tajikistani Ruble',
            self::TJS => 'Tajikistani Somoni',
            self::TMM => 'Turkmenistani Manat (1993–2009)',
            self::TMT => 'Turkmenistani Manat',
            self::TND => 'Tunisian Dinar',
            self::TOP => 'Tongan Paʻanga',
            self::TPE => 'Timorese Escudo',
            self::TRL => 'Turkish Lira (1922–2005)',
            self::TRY => 'Turkish Lira',
            self::TTD => 'Trinidad & Tobago Dollar',
            self::TWD => 'New Taiwan Dollar',
            self::TZS => 'Tanzanian Shilling',
            self::UAH => 'Ukrainian Hryvnia',
            self::UAK => 'Ukrainian Karbovanets',
            self::UGS => 'Ugandan Shilling (1966–1987)',
            self::UGX => 'Ugandan Shilling',
            self::USD => 'US Dollar',
            self::USN => 'US Dollar (Next day)',
            self::USS => 'US Dollar (Same day)',
            self::UYI => 'Uruguayan Peso (Indexed Units)',
            self::UYP => 'Uruguayan Peso (1975–1993)',
            self::UYU => 'Uruguayan Peso',
            self::UYW => 'Uruguayan Nominal Wage Index Unit',
            self::UZS => 'Uzbekistani Som',
            self::VEB => 'Venezuelan Bolívar (1871–2008)',
            self::VED => 'Bolívar Soberano',
            self::VEF => 'Venezuelan Bolívar (2008–2018)',
            self::VES => 'Venezuelan Bolívar',
            self::VND => 'Vietnamese Dong',
            self::VNN => 'Vietnamese Dong (1978–1985)',
            self::VUV => 'Vanuatu Vatu',
            self::WST => 'Samoan Tala',
            self::XAF => 'Central African CFA Franc',
            self::XAG => 'Silver',
            self::XAU => 'Gold',
            self::XBA => 'EURCO (European Composite Unit)',
            self::XBB => 'EMU-6 (European Monetary Unit)',
            self::XBC => 'EUA-9 (European Unit of Account-9)',
            self::XBD => 'EUA-17 (European Unit of Account-17)',
            self::XCD => 'East Caribbean Dollar',
            self::XDR => 'SDR INTL Monetary Fund (I.M.F.)',
            self::XEU => 'European Currency Unit',
            self::XFO => 'French Gold Franc',
            self::XFU => 'French UIC-Franc',
            self::XOF => 'West African CFA Franc',
            self::XPD => 'Palladium',
            self::XPF => 'CFP Franc',
            self::XPT => 'Platinum',
            self::XRE => 'RINET Funds',
            self::XSU => 'SUCRE (Unit of Account)',
            self::XUA => 'ADB (Unit of Account)',
            self::XXX => 'Transactions Without Currency',
            self::YDD => 'Yemeni Dinar',
            self::YER => 'Yemeni Rial',
            self::YUD => 'Yugoslavian Hard Dinar (1966–1990)',
            self::YUM => 'Yugoslavian New Dinar (1994–2002)',
            self::YUN => 'Yugoslavian Convertible Dinar (1990–1992)',
            self::YUR => 'Yugoslavian Reformed Dinar (1992–1993)',
            self::ZAL => 'South African Rand (financial)',
            self::ZAR => 'South African Rand',
            self::ZMK => 'Zambian Kwacha (1968–2012)',
            self::ZMW => 'Zambian Kwacha',
            self::ZRN => 'Zairean New Zaire (1993–1998)',
            self::ZRZ => 'Zairean Zaire (1971–1993)',
            self::ZWD => 'Zimbabwean Dollar (1980–2008)',
            self::ZWL => 'Zimbabwean Dollar (2009)',
            self::ZWR => 'Zimbabwean Dollar (2008)',
        };
    }

    /**
     * Returns currency decimal place number.
     */
    public function getDecimalPlace(): int
    {
        return match ($this) {
            self::BIF, self::CLP, self::DJF, self::GNF, self::ISK, self::JPY, self::KMF, self::KRW, self::PYG, self::RWF, self::UGX, self::UYI, self::VND, self::VUV, self::XAF, self::XOF, self::XPF, self::XSU, self::XUA => 0,
            self::BHD, self::IQD, self::JOD, self::KWD, self::LYD, self::OMR, self::TND => 3,
            self::CLF, self::UYW => 4,
            self::XAG, self::XAU, self::XBA, self::XBB, self::XBC, self::XBD, self::XDR, self::XPD, self::XPT, self::XXX => 5,
            default => 2,
        };
    }
    case ADP = 'ADP';
    case AED = 'AED';
    case AFA = 'AFA';
    case AFN = 'AFN';
    case ALK = 'ALK';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ANG = 'ANG';
    case AOA = 'AOA';
    case AOK = 'AOK';
    case AON = 'AON';
    case AOR = 'AOR';
    case ARA = 'ARA';
    case ARL = 'ARL';
    case ARM = 'ARM';
    case ARP = 'ARP';
    case ARS = 'ARS';
    case ATS = 'ATS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZM = 'AZM';
    case AZN = 'AZN';
    case BAD = 'BAD';
    case BAM = 'BAM';
    case BAN = 'BAN';
    case BBD = 'BBD';
    case BDT = 'BDT';
    case BEC = 'BEC';
    case BEF = 'BEF';
    case BEL = 'BEL';
    case BGL = 'BGL';
    case BGM = 'BGM';
    case BGN = 'BGN';
    case BGO = 'BGO';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BOL = 'BOL';
    case BOP = 'BOP';
    case BOV = 'BOV';
    case BRB = 'BRB';
    case BRC = 'BRC';
    case BRE = 'BRE';
    case BRL = 'BRL';
    case BRN = 'BRN';
    case BRR = 'BRR';
    case BRZ = 'BRZ';
    case BSD = 'BSD';
    case BTN = 'BTN';
    case BUK = 'BUK';
    case BWP = 'BWP';
    case BYB = 'BYB';
    case BYN = 'BYN';
    case BYR = 'BYR';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CDF = 'CDF';
    case CHE = 'CHE';
    case CHF = 'CHF';
    case CHW = 'CHW';
    case CLE = 'CLE';
    case CLF = 'CLF';
    case CLP = 'CLP';
    case CNH = 'CNH';
    case CNX = 'CNX';
    case CNY = 'CNY';
    case COP = 'COP';
    case COU = 'COU';
    case CRC = 'CRC';
    case CSD = 'CSD';
    case CSK = 'CSK';
    case CUC = 'CUC';
    case CUP = 'CUP';
    case CVE = 'CVE';
    case CYP = 'CYP';
    case CZK = 'CZK';
    case DDM = 'DDM';
    case DEM = 'DEM';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case ECS = 'ECS';
    case ECV = 'ECV';
    case EEK = 'EEK';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ESA = 'ESA';
    case ESB = 'ESB';
    case ESP = 'ESP';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FIM = 'FIM';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case FRF = 'FRF';
    case GBP = 'GBP';
    case GEK = 'GEK';
    case GEL = 'GEL';
    case GHC = 'GHC';
    case GHS = 'GHS';
    case GIP = 'GIP';
    case GMD = 'GMD';
    case GNF = 'GNF';
    case GNS = 'GNS';
    case GQE = 'GQE';
    case GRD = 'GRD';
    case GTQ = 'GTQ';
    case GWE = 'GWE';
    case GWP = 'GWP';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRD = 'HRD';
    case HRK = 'HRK';
    case HTG = 'HTG';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case IEP = 'IEP';
    case ILP = 'ILP';
    case ILR = 'ILR';
    case ILS = 'ILS';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISJ = 'ISJ';
    case ISK = 'ISK';
    case ITL = 'ITL';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KPW = 'KPW';
    case KRH = 'KRH';
    case KRO = 'KRO';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LSL = 'LSL';
    case LTL = 'LTL';
    case LTT = 'LTT';
    case LUC = 'LUC';
    case LUF = 'LUF';
    case LUL = 'LUL';
    case LVL = 'LVL';
    case LVR = 'LVR';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MAF = 'MAF';
    case MCF = 'MCF';
    case MDC = 'MDC';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MGF = 'MGF';
    case MKD = 'MKD';
    case MKN = 'MKN';
    case MLF = 'MLF';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MOP = 'MOP';
    case MRO = 'MRO';
    case MRU = 'MRU';
    case MTL = 'MTL';
    case MTP = 'MTP';
    case MUR = 'MUR';
    case MVP = 'MVP';
    case MVR = 'MVR';
    case MWK = 'MWK';
    case MXN = 'MXN';
    case MXP = 'MXP';
    case MXV = 'MXV';
    case MYR = 'MYR';
    case MZE = 'MZE';
    case MZM = 'MZM';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIC = 'NIC';
    case NIO = 'NIO';
    case NLG = 'NLG';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEI = 'PEI';
    case PEN = 'PEN';
    case PES = 'PES';
    case PGK = 'PGK';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PLZ = 'PLZ';
    case PTE = 'PTE';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RHD = 'RHD';
    case ROL = 'ROL';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RUR = 'RUR';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SDD = 'SDD';
    case SDG = 'SDG';
    case SDP = 'SDP';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SIT = 'SIT';
    case SKK = 'SKK';
    case SLE = 'SLE';
    case SLL = 'SLL';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case SRG = 'SRG';
    case SSP = 'SSP';
    case STD = 'STD';
    case STN = 'STN';
    case SUR = 'SUR';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case SZL = 'SZL';
    case THB = 'THB';
    case TJR = 'TJR';
    case TJS = 'TJS';
    case TMM = 'TMM';
    case TMT = 'TMT';
    case TND = 'TND';
    case TOP = 'TOP';
    case TPE = 'TPE';
    case TRL = 'TRL';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UAK = 'UAK';
    case UGS = 'UGS';
    case UGX = 'UGX';
    case USD = 'USD';
    case USN = 'USN';
    case USS = 'USS';
    case UYI = 'UYI';
    case UYP = 'UYP';
    case UYU = 'UYU';
    case UYW = 'UYW';
    case UZS = 'UZS';
    case VEB = 'VEB';
    case VED = 'VED';
    case VEF = 'VEF';
    case VES = 'VES';
    case VND = 'VND';
    case VNN = 'VNN';
    case VUV = 'VUV';
    case WST = 'WST';
    case XAF = 'XAF';
    case XAG = 'XAG';
    case XAU = 'XAU';
    case XBA = 'XBA';
    case XBB = 'XBB';
    case XBC = 'XBC';
    case XBD = 'XBD';
    case XCD = 'XCD';
    case XDR = 'XDR';
    case XEU = 'XEU';
    case XFO = 'XFO';
    case XFU = 'XFU';
    case XOF = 'XOF';
    case XPD = 'XPD';
    case XPF = 'XPF';
    case XPT = 'XPT';
    case XRE = 'XRE';
    case XSU = 'XSU';
    case XUA = 'XUA';
    case XXX = 'XXX';
    case YDD = 'YDD';
    case YER = 'YER';
    case YUD = 'YUD';
    case YUM = 'YUM';
    case YUN = 'YUN';
    case YUR = 'YUR';
    case ZAL = 'ZAL';
    case ZAR = 'ZAR';
    case ZMK = 'ZMK';
    case ZMW = 'ZMW';
    case ZRN = 'ZRN';
    case ZRZ = 'ZRZ';
    case ZWD = 'ZWD';
    case ZWL = 'ZWL';
    case ZWR = 'ZWR';
}
